### ISSUE TITLE
source jekyll

### ISSUE THREAD

**Issue by tigefa4u** [GitIndonesia/GitIndonesia.github.io#1]
lebih bagus ada source jekyll nya :+1: @SunDi3yansyah @zhiephie

**Comment by SunDi3yansyah** [comment]
berarti ambil semuanya sampe _config.yml dst, iya mas..?

**Comment by tigefa4u** [comment]
@SunDi3yansyah iya mas, seperti ini https://github.com/jglovier/jekyll-new ini source default `jekyll new helloworld` themplate.

**Comment by zhiephie** [comment]
ayolah

**Comment by SunDi3yansyah** [comment]
sudah bang :dancer:  silakan di clone, kalau ada yg salah di benarkan yak :+1:

**Comment by zhiephie** [comment]
:kissing_heart:

**Comment by rizkylab** [comment]
:+1:
