### ISSUE TITLE
jones

### ISSUE THREAD

**Issue by dikiaap** [GitIndonesia/GitIndonesia.github.io#2]

**Comment by dikiaap** [comment]
Ganti dong nama reponya, biar site nya bisa diakses lagi :joy:

**Comment by SunDi3yansyah** [comment]
udah wooyy wowkwowko
tapi web nya belum berubah, harus di commit lg ini yg branch master

**Comment by dikiaap** [comment]
Commit lg @wicky-info

**Comment by wicky-andrian** [comment]
aduu brother soryy blm cek ,, oke oke

**Comment by wicky-andrian** [comment]
@dikiaap  bro udh ka ? git add --all  , git commit -m "gini aja kan "  , git push origin master ..

**Comment by wicky-andrian** [comment]
jones mania , aku udh commit ada 2 "master " dan "source"  ..it gmna yaa .. maksudnya biar yg master bisa di commit bebas apa gmna gtu ..

**Comment by SunDi3yansyah** [comment]
https://github.com/GitIndonesia/GitIndonesia.github.io/blob/master/README.md

buka folder `/path/repo/.git/config` ganti URL repo yang sekarang

**Comment by wicky-andrian** [comment]
oke mastah

**Comment by wicky-andrian** [comment]
mastah udh aku ganti ..

**Comment by wicky-andrian** [comment]
kok malah gak ada last commit ..malal everything up to date
![screenshot from 2015-10-03 01 05 11](https://cloud.githubusercontent.com/assets/8560064/10253962/d4da0536-696a-11e5-8f3d-5fcf1203cea4.png)

**Comment by SunDi3yansyah** [comment]
IYa emang gk ada, itu config... dan sudah benar begitu di rubah bagian ini saja
`url = git@github.com:GitHubIndonesia/githubindonesia.github.io.git` jadi seperti ini `url = git@github.com:GitIndonesia/GitIndonesia.github.io.git`
kalau mau liat last commit ya ketik aja `git log` di folder reponya

![screenshot from 2015-10-03 05 33 20](https://cloud.githubusercontent.com/assets/3952281/10259251/504486fe-6990-11e5-9fd5-b0cf974d8e61.png)

**Comment by wicky-andrian** [comment]
oke siap mastah

**Comment by wicky-andrian** [comment]
![screenshot from 2015-10-03 11 26 23](https://cloud.githubusercontent.com/assets/8560064/10261434/9e875dc4-69c1-11e5-88a3-9a056eeb5230.png)

**Comment by wicky-andrian** [comment]
![screenshot from 2015-10-03 11 27 21](https://cloud.githubusercontent.com/assets/8560064/10261438/c472e88c-69c1-11e5-95a3-e654b2d01c3c.png)

**Comment by wicky-andrian** [comment]
sdh mastah , sdh aku gantii
