### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by tigefa4u** [GitIndonesia/GitIndonesia.github.io#3]
ini domainnya udah gak bisa di akses? :fire_engine:

**Comment by SunDi3yansyah** [comment]
https://github.com/GitIndonesia/GitIndonesia.github.io/blob/master/CNAME
Expires domain :dancer: cari yang halal saja :smile:

**Comment by tigefa4u** [comment]
ok :+1:
tapi gak harus pake CNAME file kalau `github.io`
tak hapus ya :sandal:

**Comment by SunDi3yansyah** [comment]
oh ya lupa ajajajjaj :smile:
