### ISSUE TITLE
???????????????????????

### ISSUE THREAD

**Issue by dikiaap** [GitIndonesia/GitIndonesia.github.io#4]
Baru ane update template nya. Gpp kan? Yg lama udah ane backup di release / di branch source masih ada :smile:

Problem
- di link navigasi https dll, kliru pake http.
- Banyak lorem lorem nya juga

**Comment by SunDi3yansyah** [comment]
Saya lebih suka yang sekarang :+1:  nice :dancer: karena yang lama:
- [x] Jarang ada yang mau edit-edit gitu
- [x] Templatenya terlalu rame
- [x] Terlalu bejibun isinya

**Comment by dikiaap** [comment]
Wkwk, thank you :v
Itu cuma nambahin translate + edit css.

**Comment by SunDi3yansyah** [comment]
Tidak apa-apa, dari pada terdiam dan tidak tau jalan pulang :smile:

**Comment by dikiaap** [comment]
malah nyanyi :laughing: 
https://www.youtube.com/watch?v=b3SavYKhmxs

**Comment by rizkylab** [comment]
aku Suka @dikiaap

**Comment by dikiaap** [comment]
jangan tambahin username ku di belakang kaya gitu. :dancer:

**Comment by rizkylab** [comment]
hahaa.. akur dah sama om @SunDi3yansyah ... lebih suka yang sekarang ..ntap!!

**Comment by dikiaap** [comment]
Ntap om @rizkylab :smile:
