### ISSUE TITLE
Redisain situs, beralih ke Bootstrap murni.

### ISSUE THREAD

**Issue by indrakaw** [GitIndonesia/GitIndonesia.github.io#5]
Belakangan ini, saya kembangkan situs @GitIndonesia ke framework Bootstrap murni, dengan beberapa tambahan. Anda dapat melihatnya di:
- Tree: [develop tree](https://github.com/indrakaw/GitIndonesia.github.io/tree/develop) pada @indrakaw, atau
- [Live Development site](http://gitindonesia.netlify.com/) (build hasil tree `develop`).

Masih belum selesain dan perlu pembenahan lagi! 
Suatu saat akan di-merge ke repo ini!

Namanya member baru, saya krisis informasi tentang apa itu Git Indonesia. Banyak konten masih kosong, dan harus diisi. Saya meminta kepada member yang sudah bertahun-tahun agar mengisinya.

Mohon responnya!

-Indra

**Comment by dikiaap** [comment]
Thanks kontribusinya @indrakaw.

Tema disini baru saja saya ganti bulan lalu. Menurutku kalo pakai bootstrap murni, terlalu mainstream tampilannya dengan situs-situs lainnya.

Saya prefer ke tema yang sudah jadi, saya ambil di http://jekyllthemes.org
Ini sumber tema sekarang https://github.com/CloudCannon/DopeTrope-Jekyll-Theme
Kita tinggal customize tema yang sudah jadi.
Kalo udah ada yang jadi, kenapa harus buat ulang. Hm.
Dan kita tinggal mengisi konten yang ada.

Karena member disini juga pasti banyak yang sibuk dengan kegiatan masing-masing, kemungkinan sedikit yang merespon.

**Comment by dikiaap** [comment]
Kalo mau membangun website gitindo dr awal sampai selesai silahkan mas, website nya jadi dan bisa memberikan info kepada orang2 yg mengunjunginya. Saya siap membantu. Dan dibedakan jg dg web lain, harus ada goresan sdkt :smile:
Kalo bisa, saya jadiin member utk ngurus repo ini, bagaimana?

**Comment by indrakaw** [comment]
Dimengerti @dikiaap. :ok_hand: 

Jadikan member? Tentu saya akan sangat senang sekali! Tapi saya nggak akan lakukan direct commit atau jika akan ubah sesuatu--harus lewat Pull Request.

Kalau bisa, cantumkan saka ke organiasai @GitIndonesia saja. :smile: 

Juga, saya alami sedikit masalah...
![can t auto-merge](https://cloud.githubusercontent.com/assets/9590878/14551273/1815df94-02fb-11e6-92aa-d287ce56fb1d.png)

Belum pernah alami ini sebelumnya. :neutral_face:
Ada solusi? Haruskah saya langsung dibuat PR saja?

**Comment by dikiaap** [comment]
Silahkan cek email nya.

**Comment by wicky-andrian** [comment]
joss ..joss
